### ISSUE TITLE
ETags - how do we handle our data to be easily cached?

### ISSUE THREAD

**Issue by PureKrome** [Homely/Homely.AspNetCore.WebApi.Template#9]
How can our data (via a `GET` request) be easily cached?

- Do we want to just create an E-Tag on the response (based on the payload data, of course)
- Do we care that, if a request arrives with some E-Tag header, we check an in-memory cache of previously determined responses? This means ... we'll be storing stuff in In-Mem RAM ...

**Comment by PureKrome** [comment]
Suggestion is to use [Fastly](https://www.fastly.com/) and [then manually purge via keys](https://docs.fastly.com/guides/purging/single-purges#purging-with-keys). This way, the url's a client does an `HTTP GET` to, will either exist in Fastly, or be manually purged by us.

To control Fastly caching - [set the cache headers](https://docs.fastly.com/guides/performance-tuning/controlling-caching) as required by your own requirements/data.

**Comment by RPM1984** [comment]
Hack demonstrating viability: https://github.com/Homely/Homely.HackDays.CDNCachedAPI
